### PR TITLE
[DEV] Update to 0.22.0rc2

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@jhkennedy, let me know if you'd like me to remove you as a maintainer here (and also for TempestRemap).  I'm certainly happy to have you here but if you don't want the extra email traffic, I'll be happy to leave you be.

**Comment by jhkennedy** [comment]
> @jhkennedy, let me know if you'd like me to remove you as a maintainer here (and also for TempestRemap). I'm certainly happy to have you here but if you don't want the extra email traffic, I'll be happy to leave you be.

@xylar Sorry for the *incredibly* slow reply -- I was out on paternity leave at the time and this got buried. Since I'm the only other maintainer (here and there), it's probably worth leaving me as a backup if you're indisposed. I don't mind the traffic :-D 

But I'm def. not an active maintainer at this point, so I don't mind being dropped if you'd prefer.

**Comment by xylar** [comment]
@jhkennedy, great to know. I'm definitely happy to have you on both, so we'll leave it as is. I just wanted to make sure.

**Pull request merged**
